### PR TITLE
Update test_Course.py

### PR DESCRIPTION
**Pull request by bruggin9**
Updated the test_Course file to match the updated CourseManagement.py file to the best of my ability. Feel free to make any changes if I did anything wrong.

### CODE REVIEW

**Comment by YazanSalem** [comment]
Looks good for the most part, the courseID in an integer field not a string so when testing methods that ask for a courseID to pass in an int. Other than that it looks good, good job.

**Comment by BMHebert** [comment]
I attempted to run the tests on my machine but it seems that there are old parts of the code left in that prevent it from running. Were you able to run any of these tests on your computer before making the pull requests?

**Comment by bruggin9** [comment]
Yes you are right, I didn't update the project properly before making the tests. My fault. I did take a look at your tests and will make a comment momentarily on those. We can cancel this pull request if that makes more sense.

**Comment by BMHebert** [comment]
Ok, I've taken a look at your code in more detail and attempted some debugging, but I think at this point it might just be easier to go ahead and merge my branch since it's already functional if you find no problems there. Sorry about the miscommunication.

**Comment by bruggin9** [comment]
Yes I agree, I apologize I should've not been working on this when you already were. Considering yours actually work as well, yes I agree we should go ahead with yours.

**Pull request closed without merging**
