### PR TITLE
Wrote tests for CourseManagement

### PR DESCRIPTION
**Pull request by BMHebert**
Updated tests for CourseManagement to work properly and slightly modified CourseManagement to work smoother. This is specifically for Sam to look at to see what we can take from each of our implementations to merge together into one set of tests.

### CODE REVIEW

**Comment by bruggin9** [comment]
All of your tests look good, yours are much clearer than mine were. I did have some comments/questions. For the CourseID, CourseName and CourseLocation tests, I was wondering if you wanted to include an invalid test as well for each one of those like you did with courseDays? As well as for the TA/Instructor ones, there were two Instructor/TA objects created. I was wondering if that test would overlap and cause a problem or if those are fine? Otherwise everything looks great.

**Comment by BMHebert** [comment]
Regarding the tests dealing with 2 instructors and TAs, having two was intentional since the editCourse method is meant to be able to edit all fields of the course, including the Instructor and TAs fields. This means that to edit those fields, there needs to be an instructor and a TA that was there initially, and one to change it to. It works as intended in my current implementation. On the topic of writing negative tests for ID, name, and location, I think I will indeed do that. Thanks for that idea.

**Comment by bruggin9** [comment]
Okay that makes much more sense. Glad I could help with the negative tests.

**Comment by BMHebert** [comment]
Alright, I've written those new tests and cleaned up a few things.

**Review by bruggin9 — APPROVED** [review]
Looks Great!

**Pull request merged**
