### PR TITLE
Created a view to allow login

### PR DESCRIPTION
**Pull request by BMHebert**
Added in a view in views.py that processes user input on the Login page and checks if the user is valid. If so, checks the password. If not, a new user is created.

### CODE REVIEW

**Comment by cogii** [comment]
I took a quick look at the code, looks good to me!

**Review by cogii — APPROVED** [review]
Looks good to me!

**Comment by bruggin9** [comment]
Yes those changes look great. I have been trying to figure out how the redirects work, but those changes looked good.

**Review by bruggin9 — APPROVED** [review]
Looks good!

**Pull request merged**
